export const data = {
  users: [
    {
      id: 1,
      username: "",
      color: "#f50e37",
      pionNumber: 0,
      score: 0,
      gameLimit: 7,
      winNumber: 0,
      lostNumber: 0,
    },
    {
      id: 2,
      username: "",
      color: "#4724f0",
      pionNumber: 0,
      score: 0,
      gameLimit: 7,
      winNumber: 0,
      lostNumber: 0,
    },
  ],
  party: {
    isFilling: true,
    isMoving: false,
    isCutting: false,
    tourId: 1,
    tourNumber: 1,
    selected: "",
    firstPlayer: 1,
    cuttedPions: [],
  },
  pions: [
    {
      id: 1,
      ownerId: 0,
      color: "gray",
      abs: 0,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 2,
      ownerId: 0,
      color: "gray",
      abs: 0,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 3,
      ownerId: 0,
      color: "gray",
      abs: 0,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 4,
      ownerId: 0,
      color: "gray",
      abs: 0,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 5,
      ownerId: 0,
      color: "gray",
      abs: 0,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 6,
      ownerId: 0,
      color: "gray",
      abs: 1,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 7,
      ownerId: 0,
      color: "gray",
      abs: 1,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 8,
      ownerId: 0,
      color: "gray",
      abs: 1,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 9,
      ownerId: 0,
      color: "gray",
      abs: 1,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 10,
      ownerId: 0,
      color: "gray",
      abs: 1,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 11,
      ownerId: 0,
      color: "gray",
      abs: 2,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 12,
      ownerId: 0,
      color: "gray",
      abs: 2,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 13,
      ownerId: 0,
      color: "gray",
      abs: 2,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 14,
      ownerId: 0,
      color: "gray",
      abs: 2,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 15,
      ownerId: 0,
      color: "gray",
      abs: 2,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 16,
      ownerId: 0,
      color: "gray",
      abs: 3,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 17,
      ownerId: 0,
      color: "gray",
      abs: 3,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 18,
      ownerId: 0,
      color: "gray",
      abs: 3,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 19,
      ownerId: 0,
      color: "gray",
      abs: 3,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 20,
      ownerId: 0,
      color: "gray",
      abs: 3,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 21,
      ownerId: 0,
      color: "gray",
      abs: 4,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 22,
      ownerId: 0,
      color: "gray",
      abs: 4,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 23,
      ownerId: 0,
      color: "gray",
      abs: 4,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 24,
      ownerId: 0,
      color: "gray",
      abs: 4,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 25,
      ownerId: 0,
      color: "gray",
      abs: 4,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 26,
      ownerId: 0,
      color: "gray",
      abs: 5,
      ord: 0,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 27,
      ownerId: 0,
      color: "gray",
      abs: 5,
      ord: 1,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 28,
      ownerId: 0,
      color: "gray",
      abs: 5,
      ord: 2,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 29,
      ownerId: 0,
      color: "gray",
      abs: 5,
      ord: 3,
      isSelected: false,
      isValidMove: false,
    },
    {
      id: 30,
      ownerId: 0,
      color: "gray",
      abs: 5,
      ord: 4,
      isSelected: false,
      isValidMove: false,
    },
  ],
};
